--ozone-platform-hint=auto
--gtk-version=4
--ignore-gpu-blocklist
--enable-features=UseOzonePlatform,WaylandWindowDecorations,TouchpadOverscrollHistoryNavigation
--unity-launch
--enable-wayland-ime
--password-store=gnome-libsecret